<template>
  <div>
    <!-- <div class="title">
      <h2>流行音樂篇</h2>
    </div>
    <hr> -->
    <p class="firstRow"></p>
    <table rules="all" border="1" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:20%">負責人</th>
          <th style="width:25%">其他聯絡方式</th>
          <th>備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            臺北爵士大樂隊
          </td>
          <td>
            音樂總監 李承育
          </td>
          <td>
            www.tjo.com.tw/
          </td>
          <td>
            成立於2009年2月
          </td>
        </tr>
        <tr>
          <td>
            八三么
          </td>
          <td>
            滾石唱片
          </td>
          <td>
            https://www.band831.com/
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            盧廣仲
          </td>
          <td>
            添翼創越唱片公司
          </td>
          <td>
            www.team-ear.com/
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            茄子蛋
          </td>
          <td>
            經紀人 百萱
          </td>
          <td>
            https://www.facebook.com/EggPlantEgg/ eggplantegg2014@gmail.com
          </td>
          <td>
            成立於2012年
          </td>
        </tr>
        <tr>
          <td>
            晨曦光廊
          </td>
          <td>
            出力音樂
          </td>
          <td>
            https://www.facebook.com/SUNOFMORNING/
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            詹雅雯
          </td>
          <td>
            詹雅雯 經紀人 小良
          </td>
          <td>
            https://www.facebook.com/YW.FanClub/ yiawen0302@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            家家
          </td>
          <td>
            相信音樂國際股份有限公司
          </td>
          <td>
            https://www.facebook.com/JiaJiaMyLove/ hsuben0624@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            呂薔
          </td>
          <td>
            avex taiwan 愛貝克思股份有限公司
          </td>
          <td>
            https://www.facebook.com/AmuyiLu/
          </td>
          <td>
            2013年出道
          </td>
        </tr>
        <tr>
          <td>
            董事長樂團
          </td>
          <td>
            大吉祥整合行銷有限公司
          </td>
          <td>
            https://www.facebook.com/chairman.taiwan/ summerwang825@gmail.com
          </td>
          <td>
            成立於1997年
          </td>
        </tr>
        <tr>
          <td>
            閃靈樂團
          </td>
          <td>
            環球唱片
          </td>
          <td>
            https://www.facebook.com/chthonictw/ invalinews@gmail.com
          </td>
          <td>
            主唱為立法委員林昶佐
          </td>
        </tr>
        <tr>
          <td>
            美秀集團
          </td>
          <td>
            Bully
          </td>
          <td>
            https://www.facebook.com/amazingshowtw/ amazingshowcy@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            李玟
          </td>
          <td>
            CL Production Ltd
          </td>
          <td>
            https://www.facebook.com/cocolee117/ vjdust@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            伍佰
          </td>
          <td>
            月光音樂
          </td>
          <td>
            https://www.facebook.com/wubaiclub/
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            阿爆
          </td>
          <td></td>
          <td>
            https://www.facebook.com/ABAO825/
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            萬芳
          </td>
          <td></td>
          <td>
            https://www.facebook.com/iamOneFang/ lin.fade@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            蕭秉治
          </td>
          <td>
            相信音樂
          </td>
          <td>
            https://www.facebook.com/BingChih/ xiaobingchih@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            紀曉君
          </td>
          <td>
            紀曉君個人工作室
          </td>
          <td>
            https://www.facebook.com/Samingad/ gary720613@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            吳青峰
          </td>
          <td>
            哈里坤的狂歡
          </td>
          <td>
            https://www.facebook.com/WuQingFeng/ u.music@foxmail.com Oscar.lin@umusic.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            打幫你樂團
          </td>
          <td>
            Leo黎歐創意
          </td>
          <td>
            https://www.facebook.com/DaBangNi/ dabangni@gmail.com
          </td>
          <td>
            成立於2011年12月
          </td>
        </tr>
        <tr>
          <td>
            陳永淘
          </td>
          <td></td>
          <td>
            https://www.facebook.com/ataogomusic/
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            黃瑋傑
          </td>
          <td></td>
          <td>
            https://www.facebook.com/huangweijieweijie/ shanliaoband@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            曾仲瑋
          </td>
          <td></td>
          <td>
            https://www.facebook.com/hakkarobin/
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            桑布伊
          </td>
          <td>
            卡達德邦文化工作室
          </td>
          <td>
            https://www.facebook.com/Sangpuy/
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            徹摩
          </td>
          <td>
            漢創文化股份有限公司
          </td>
          <td>
            mavislin@hgcagroup.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            黃連煜
          </td>
          <td>
            貳樓音樂
          </td>
          <td>
            https://www.facebook.com/ayugohuang/ ayugo814@gmail.com
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            舒米恩
          </td>
          <td>
            亞神音樂
          </td>
          <td>
            https://www.sumingfans.com/ johnsuming@gmail.com
          </td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
